# Generated by Django 5.0.1 on 2024-06-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingCard',
            fields=[
                ('card_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entry_image', models.ImageField(upload_to='images/entries/')),
                ('exit_image', models.ImageField(blank=True, null=True, upload_to='images/exits/')),
                ('parking_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingCar.parkingcard')),
            ],
        ),
    ]
